image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:

  - ps: $App = Start-Process -FilePath java -ArgumentList "-jar ./artifacts/app-card-delivery.jar" -PassThru

build_script:
  - ps:  chmod +x gradlew
  - ps: ./gradlew test --info "-Dselenide.headless=true"

on_finish:
  - ps: Stop-Process -Id $App.Id